[test]
# Use jsdom to align with setupTests.ts
environment = "jsdom"
preload = ["./setupTests.ts"]
coverage = true
timeout = 5000
# Exclude the Playwright tests directory
exclude = ["./tests/**"]

# Removed [test.dom] section as setup.ts handles DOM setup manually
