"""add store hours columns

Revision ID: 460ec5407d2a
Revises: 
Create Date: 2025-02-19 13:47:28.168088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460ec5407d2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_days', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('special_hours', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('special_hours')
        batch_op.drop_column('opening_days')

    # ### end Alembic commands ###
