"""Add version column to schedules table

Revision ID: add_version_column
Revises: be95b36a000c
Create Date: 2025-02-28 00:18:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_version_column"
down_revision = "be95b36a000c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("version", sa.Integer(), nullable=False, server_default="1")
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.drop_column("version")
    # ### end Alembic commands ###
