"""add theme colors and dark theme support

Revision ID: bc4f1654eea7
Revises: c1b9ace20ec1
Create Date: 2025-02-21 00:30:30.310187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4f1654eea7'
down_revision = 'c1b9ace20ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accent_color', sa.String(length=7), nullable=False, server_default='#FF4081'))
        batch_op.add_column(sa.Column('background_color', sa.String(length=7), nullable=False, server_default='#FFFFFF'))
        batch_op.add_column(sa.Column('surface_color', sa.String(length=7), nullable=False, server_default='#F5F5F5'))
        batch_op.add_column(sa.Column('text_color', sa.String(length=7), nullable=False, server_default='#212121'))
        batch_op.add_column(sa.Column('dark_theme_primary_color', sa.String(length=7), nullable=False, server_default='#90CAF9'))
        batch_op.add_column(sa.Column('dark_theme_secondary_color', sa.String(length=7), nullable=False, server_default='#757575'))
        batch_op.add_column(sa.Column('dark_theme_accent_color', sa.String(length=7), nullable=False, server_default='#FF80AB'))
        batch_op.add_column(sa.Column('dark_theme_background_color', sa.String(length=7), nullable=False, server_default='#121212'))
        batch_op.add_column(sa.Column('dark_theme_surface_color', sa.String(length=7), nullable=False, server_default='#1E1E1E'))
        batch_op.add_column(sa.Column('dark_theme_text_color', sa.String(length=7), nullable=False, server_default='#FFFFFF'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('dark_theme_text_color')
        batch_op.drop_column('dark_theme_surface_color')
        batch_op.drop_column('dark_theme_background_color')
        batch_op.drop_column('dark_theme_accent_color')
        batch_op.drop_column('dark_theme_secondary_color')
        batch_op.drop_column('dark_theme_primary_color')
        batch_op.drop_column('text_color')
        batch_op.drop_column('surface_color')
        batch_op.drop_column('background_color')
        batch_op.drop_column('accent_color')

    # ### end Alembic commands ###
