"""Add pdf_layout_presets column to settings

Revision ID: be95b36a000c
Revises: remove_keyholder_fields
Create Date: 2025-02-27 16:03:58.426864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be95b36a000c'
down_revision = 'remove_keyholder_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coverage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyholder_before_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('keyholder_after_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('break_start', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('break_end', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'shifts', ['shift_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'shifts', ['shift_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('break_end')
        batch_op.drop_column('break_start')
        batch_op.drop_column('version')

    with op.batch_alter_table('coverage', schema=None) as batch_op:
        batch_op.drop_column('keyholder_after_minutes')
        batch_op.drop_column('keyholder_before_minutes')

    # ### end Alembic commands ###
