"""add notes field to schedule

Revision ID: c7d93ab77f3d
Revises: update_settings_table
Create Date: 2025-02-18 18:31:46.590895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d93ab77f3d'
down_revision = 'update_settings_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=200), nullable=True))
        batch_op.alter_column('break_start',
               existing_type=sa.TIME(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('break_end',
               existing_type=sa.TIME(),
               type_=sa.String(length=5),
               existing_nullable=True)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('key', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('value', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uix_category_key', ['category', 'key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint('uix_category_key', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('value')
        batch_op.drop_column('key')
        batch_op.drop_column('category')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('break_end',
               existing_type=sa.String(length=5),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('break_start',
               existing_type=sa.String(length=5),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
