"""Initial migration

Revision ID: de3c6a13df0a
Revises:
Create Date: 2025-03-09 07:55:13.449959

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "de3c6a13df0a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status", sa.String(length=20), nullable=False, server_default="draft"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.drop_column("status")

    op.create_table(
        "_alembic_tmp_settings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("store_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("store_address", sa.VARCHAR(length=200), nullable=True),
        sa.Column("store_contact", sa.VARCHAR(length=100), nullable=True),
        sa.Column("timezone", sa.VARCHAR(length=50), nullable=False),
        sa.Column("language", sa.VARCHAR(length=10), nullable=False),
        sa.Column("date_format", sa.VARCHAR(length=20), nullable=False),
        sa.Column("time_format", sa.VARCHAR(length=10), nullable=False),
        sa.Column("store_opening", sa.VARCHAR(length=5), nullable=False),
        sa.Column("store_closing", sa.VARCHAR(length=5), nullable=False),
        sa.Column("pdf_layout_presets", sqlite.JSON(), nullable=True),
        sa.Column("keyholder_before_minutes", sa.INTEGER(), nullable=False),
        sa.Column("keyholder_after_minutes", sa.INTEGER(), nullable=False),
        sa.Column("opening_days", sqlite.JSON(), nullable=False),
        sa.Column("special_hours", sqlite.JSON(), nullable=False),
        sa.Column("availability_types", sqlite.JSON(), nullable=True),
        sa.Column("scheduling_resource_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("default_shift_duration", sa.FLOAT(), nullable=False),
        sa.Column("min_break_duration", sa.INTEGER(), nullable=False),
        sa.Column("max_daily_hours", sa.FLOAT(), nullable=False),
        sa.Column("max_weekly_hours", sa.FLOAT(), nullable=False),
        sa.Column("min_rest_between_shifts", sa.FLOAT(), nullable=False),
        sa.Column("scheduling_period_weeks", sa.INTEGER(), nullable=False),
        sa.Column("auto_schedule_preferences", sa.BOOLEAN(), nullable=False),
        sa.Column("theme", sa.VARCHAR(length=20), nullable=False),
        sa.Column("primary_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("secondary_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("accent_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("background_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("surface_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("text_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("dark_theme_primary_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("dark_theme_secondary_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("dark_theme_accent_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("dark_theme_background_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("dark_theme_surface_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("dark_theme_text_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("show_sunday", sa.BOOLEAN(), nullable=False),
        sa.Column("show_weekdays", sa.BOOLEAN(), nullable=False),
        sa.Column("start_of_week", sa.INTEGER(), nullable=False),
        sa.Column("email_notifications", sa.BOOLEAN(), nullable=False),
        sa.Column("schedule_published_notify", sa.BOOLEAN(), nullable=False),
        sa.Column("shift_changes_notify", sa.BOOLEAN(), nullable=False),
        sa.Column("time_off_requests_notify", sa.BOOLEAN(), nullable=False),
        sa.Column("page_size", sa.VARCHAR(length=10), nullable=False),
        sa.Column("orientation", sa.VARCHAR(length=10), nullable=False),
        sa.Column("margin_top", sa.FLOAT(), nullable=False),
        sa.Column("margin_right", sa.FLOAT(), nullable=False),
        sa.Column("margin_bottom", sa.FLOAT(), nullable=False),
        sa.Column("margin_left", sa.FLOAT(), nullable=False),
        sa.Column("table_header_bg_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("table_border_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("table_text_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("table_header_text_color", sa.VARCHAR(length=7), nullable=False),
        sa.Column("font_family", sa.VARCHAR(length=50), nullable=False),
        sa.Column("font_size", sa.FLOAT(), nullable=False),
        sa.Column("header_font_size", sa.FLOAT(), nullable=False),
        sa.Column("show_employee_id", sa.BOOLEAN(), nullable=False),
        sa.Column("show_position", sa.BOOLEAN(), nullable=False),
        sa.Column("show_breaks", sa.BOOLEAN(), nullable=False),
        sa.Column("show_total_hours", sa.BOOLEAN(), nullable=False),
        sa.Column("employee_types", sqlite.JSON(), nullable=False),
        sa.Column("absence_types", sqlite.JSON(), nullable=False),
        sa.Column("actions_demo_data", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
