"""Add shift_id to Coverage model

Revision ID: ed2783bafef6
Revises: 7a393576fe11
Create Date: 2025-03-01 02:27:48.688873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2783bafef6'
down_revision = '7a393576fe11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coverage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_coverage_shift', 'shifts', ['shift_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coverage', schema=None) as batch_op:
        batch_op.drop_constraint('fk_coverage_shift', type_='foreignkey')
        batch_op.drop_column('shift_id')

    # ### end Alembic commands ###
