"""Add availability_type to Schedule model

Revision ID: 0035670ff2b6
Revises: add_shift_type_to_schedules
Create Date: 2025-03-15 16:54:39.500306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0035670ff2b6'
down_revision = 'add_shift_type_to_schedules'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_type', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('availability_type')

    # ### end Alembic commands ###
