"""update_settings_model_for_pydantic_alignment

Revision ID: 57b7b9078143
Revises: 728f0b48fb1b
Create Date: 2025-05-16 11:22:47.449246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '57b7b9078143'
down_revision = '728f0b48fb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('store_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('scheduling_algorithm', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('max_generation_attempts', sa.Integer(), nullable=True))
        batch_op.drop_column('store_contact')
        batch_op.drop_column('special_hours')
        batch_op.drop_column('scheduling_advanced')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduling_advanced', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('special_hours', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('store_contact', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('max_generation_attempts')
        batch_op.drop_column('scheduling_algorithm')
        batch_op.drop_column('store_email')
        batch_op.drop_column('store_phone')

    # ### end Alembic commands ###
