"""Add week navigation settings columns to settings table

Revision ID: wn1e2e3k4n5a
Revises: 20250602_170627
Create Date: 2025-06-13 18:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'wn1e2e3k4n5a'
down_revision = '20250602_170627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        # Add week navigation columns that are missing from the database
        batch_op.add_column(sa.Column('enable_week_navigation', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('week_weekend_start', sa.String(20), nullable=False, server_default="'MONDAY'"))
        batch_op.add_column(sa.Column('week_month_boundary_mode', sa.String(30), nullable=False, server_default="'keep_intact'"))
        batch_op.add_column(sa.Column('week_navigation_default', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('week_navigation_default')
        batch_op.drop_column('week_month_boundary_mode')
        batch_op.drop_column('week_weekend_start')
        batch_op.drop_column('enable_week_navigation')

    # ### end Alembic commands ###
