"""Add total weekly working hours constraint to settings

Revision ID: f1e2d3c4b5a6
Revises: 728f0b48fb1b
Create Date: 2024-06-01 04:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e2d3c4b5a6'
down_revision = '728f0b48fb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_weekly_working_hours', sa.Float(), nullable=False, server_default='165.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('total_weekly_working_hours')

    # ### end Alembic commands ### 