"""Add week-based versioning fields to ScheduleVersionMeta

Revision ID: w1e2k3v4e5r6
Revises: f1e2d3c4b5a6
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'w1e2k3v4e5r6'
down_revision = 'f1e2d3c4b5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_version_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_identifier', sa.String(20), nullable=True))
        batch_op.add_column(sa.Column('month_boundary_mode', sa.String(20), nullable=False, server_default='keep_intact'))
        batch_op.add_column(sa.Column('is_week_based', sa.Boolean(), nullable=False, server_default='false'))

    # Add index for efficient week identifier lookups
    op.create_index('ix_schedule_version_meta_week_identifier', 'schedule_version_meta', ['week_identifier'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index first
    op.drop_index('ix_schedule_version_meta_week_identifier', 'schedule_version_meta')
    
    with op.batch_alter_table('schedule_version_meta', schema=None) as batch_op:
        batch_op.drop_column('is_week_based')
        batch_op.drop_column('month_boundary_mode')
        batch_op.drop_column('week_identifier')
    
    # ### end Alembic commands ###