"""Add ai_scheduling JSON column to settings table

Revision ID: d433bcfaf979
Revises: 0035670ff2b6
Create Date: 2025-05-11 04:23:12.349812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector # Added import


# revision identifiers, used by Alembic.
revision = 'd433bcfaf979'
down_revision = 'f1e2d3c4b5a6'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [column['name'] for column in inspector.get_columns('settings')]

    if 'ai_scheduling' not in columns:
        with op.batch_alter_table('settings', schema=None) as batch_op:
            batch_op.add_column(sa.Column('ai_scheduling', sa.JSON(), nullable=True))
            # You might want to add a default value here if appropriate, e.g.:
            # op.execute("UPDATE settings SET ai_scheduling = '{}' WHERE ai_scheduling IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('ai_scheduling')

    # ### end Alembic commands ###
