"""Add ai_scheduling JSON column to settings table

Revision ID: d433bcfaf979
Revises: 0035670ff2b6
Create Date: 2025-05-11 04:23:12.349812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd433bcfaf979'
down_revision = '0035670ff2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_scheduling', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('ai_scheduling')

    # ### end Alembic commands ###
